OC.L10N.register(
    "user_migration",
    {
    "Files" : "Файлы",
    "Data migration" : "Перенос данных",
    "**👤➡ User migration app for Nextcloud**\n\nThis app allows users to easily migrate from one instance to another using an export of their account.\n\n- **🐱 Log in to cat.example.com/nextcloud**\n- **⚙ Go into `Personal settings` > `Data migration`**\n- **☑ Select what you want to export** (settings, files, profile information, profile picture, calendars, contacts…)\n- **⚙ Start the export** and wait for the server to process it\n- **📁 Download the resulting file called `user.nextcloud_export`**\n- **🐶 Open an account on dog.example.com/nextcloud**\n- **🡅 Upload `user.nextcloud_export` into your files**\n- **⚙ Go into `Personal settings` > `Data migration` and start the import**\n- **🎉 Enjoy your stay on your new instance** and close you old account" : "**👤➡ Приложение для миграции пользователей для Nextcloud**\n\nЭто приложение позволяет пользователям легко мигрировать из одного экземпляра в другой, используя экспорт своей учетной записи.\n\n- **🐱 Войдите в cat.example.com/nextcloud**\n- **⚙ Перейдите в `Персональные настройки` > `Миграция данных`**\n- **☑ Выберите, что вы хотите экспортировать** (настройки, файлы, информацию профиля, изображение профиля, календари, контакты…)\n- **⚙ Запустите экспорт** и дождитесь, пока сервер его обработает\n- **📁 Загрузите полученный файл с именем `user.nextcloud_export`**\n- **🐶 Откройте учетную запись на dog.example.com/nextcloud**\n- **🡅 Загрузите `user.nextcloud_export` в свои файлы**\n- **⚙ Перейдите в `Персональные настройки` > `Миграция данных` и начните импорт**\n- **🎉 Наслаждайтесь пребыванием на новом экземпляре** и закройте старую учетную запись",
    "Export" : "Экспорт",
    "User information and settings" : "Информация о пользователе и настройки",
    "Basic user information including user ID and display name as well as your settings" : "Основная информация о пользователе, включая идентификатор пользователя и отображаемое имя, а также ваши настройки.",
    "Cancel" : "Отменить",
    "Close" : "Закрыть",
    "Import" : "Импортировать"
},
"nplurals=4; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : n%10==0 || (n%10>=5 && n%10<=9) || (n%100>=11 && n%100<=14)? 2 : 3);");
